// Auto-generated by `npm run export:abis`. Do not edit by hand.
// Snapshot of every recorded deployment JSON under `deployments/<network>/latest.json`.

export const eulrDeployments = {
  "generatedAt": "2026-05-21T13:25:08.970Z",
  "generatedFrom": "deployments/<network>/latest.json + out/<Contract>.sol/<Contract>.json",
  "byNetwork": {
    "anvil": {
      "network": "anvil",
      "chainId": 31337,
      "commit": "d01e3e8",
      "deployedAt": "2026-05-21T12:33:46.185Z",
      "factory": "0x1613beB3B2C4f22Ee086B2b38C1476A3cE7f78E8",
      "proxyAdmin": "0x9467A509DA43CB50EB332187602534991Be1fEa4",
      "factoryImplementation": "0xf5059a5D33d5853360D16C683c16e67980206f36",
      "hookImplementation": "0x99bbA657f2BbC93c02D617f8bA121cB8Fc104Acf",
      "routerImplementation": "0x9E545E3C0baAB3E08CdfD552C960A1050f373042",
      "feeRecipient": "0x956A587c0e0A879c179939be9907E82aB8a7CB36",
      "migrationTarget": "0xc3e53F4d16Ae77Db1c982e75a937B9f60FE63690",
      "uniswapV4PoolManager": "0x67d269191c92Caf3cD7723F116c85e6E9bf55933",
      "uniswapV4PositionManager": "0xE6E340D132b5f46d1e472DebcD681B2aBc16e57E",
      "curve": {
        "k": "21000000000000000000000000",
        "s": "100000000000000000000",
        "feeBps": 30,
        "burnTaxMinBps": 100,
        "burnTaxMaxBps": 1000,
        "selfDeprecationBps": 8000,
        "maxBuyOkb": "10000000000000000000"
      }
    },
    "forge-local": {
      "network": "forge-local",
      "chainId": 31337,
      "commit": "d1b3a27",
      "deployedAt": "2026-05-12T15:54:00.000Z",
      "factory": "0x1F585372F116E1055AF2bED81a808DDf9638dCCD",
      "feeRecipient": "0xf39Fd6e51aad88F6F4ce6aB8827279cffFb92266",
      "migrationTarget": "0xd544d7A5EF50c510f3E90863828EAba7E392907A",
      "uniswapV4PoolManager": "0x70e754531418461eF2366b72cd396337d2AD6D5d",
      "uniswapV4PositionManager": "0xeF66010868Ff77119171628B7eFa0F6179779375",
      "curve": {
        "feeBps": 30,
        "k": "21000000000000000000000000",
        "maxBuyOkb": "10000000000000000000",
        "s": "100000000000000000000",
        "selfDeprecationBps": 8000,
        "burnTaxMinBps": 0,
        "burnTaxMaxBps": 0
      }
    },
    "hashkeytest": {
      "network": "hashkeytest",
      "chainId": 133,
      "commit": "417595f",
      "deployedAt": "2026-05-14T16:33:19.907Z",
      "factory": "0x726B98099fCA8a1778EAC863Bac1232A9753a55A",
      "proxyAdmin": "0x40Fb77DEB510584D878b73E676dC62c2EaebBc87",
      "factoryImplementation": "0xB1F5802db3bD3e66A19eAb72bFd65260F931A59F",
      "routerImplementation": "0x3035c5428062B6f42cA1248baAF8Fa48338f1D7b",
      "feeRecipient": "0xd8F391e10223580611A70160d1D42bf55fCc882C",
      "migrationTarget": "0x3c5969d393197E42B4b5Fcc54055c361f2F6ACef",
      "uniswapV4PoolManager": "0xeDddAAF26109BF15E4701A61484b396DFf0A9968",
      "uniswapV4PositionManager": "0x94C6269f1D34AC47594c81c2feb9953E7cE7117E",
      "curve": {
        "k": "21000000000000000000000000",
        "s": "100000000000000000000",
        "feeBps": 30,
        "selfDeprecationBps": 8000,
        "maxBuyOkb": "10000000000000000000",
        "burnTaxMinBps": 0,
        "burnTaxMaxBps": 0
      }
    },
    "sepolia": {
      "network": "sepolia",
      "chainId": 11155111,
      "commit": "71515d5",
      "deployedAt": "2026-05-16T12:46:02Z",
      "factory": "0x659B9e6BC036535f34597c8BCBC2051B964e4a7F",
      "proxyAdmin": "0x4dDAd72B990aA5b434A5B653556D420A232E5a81",
      "factoryImplementation": "0x347f98942EE95Db4A887aa892Be5B77322ac3d02",
      "hookImplementation": "0x7462d9c9522e66C824990f4E6805F3262093526c",
      "routerImplementation": "0x4Dd48d5929baFaBd10d18D976C8F6Af35f221852",
      "feeRecipient": "0x956A587c0e0A879c179939be9907E82aB8a7CB36",
      "migrationTarget": "0x8ca7F9C9D739C582c95B3A48f9F7668AFf1A2E78",
      "uniswapV4PoolManager": "0xE03A1074c86CFeDd5C142C4F04F1a1536e203543",
      "uniswapV4PositionManager": "0x429ba70129df741B2Ca2a85BC3A2a3328e5c09b4",
      "curve": {
        "feeBps": 30,
        "k": "21000000000000000000000000",
        "maxBuyOkb": "10000000000000000000",
        "s": "100000000000000000000",
        "selfDeprecationBps": 8000,
        "burnTaxMinBps": 100,
        "burnTaxMaxBps": 1000
      }
    }
  },
  "byChainId": {
    "133": [
      {
        "network": "hashkeytest",
        "chainId": 133,
        "commit": "417595f",
        "deployedAt": "2026-05-14T16:33:19.907Z",
        "factory": "0x726B98099fCA8a1778EAC863Bac1232A9753a55A",
        "proxyAdmin": "0x40Fb77DEB510584D878b73E676dC62c2EaebBc87",
        "factoryImplementation": "0xB1F5802db3bD3e66A19eAb72bFd65260F931A59F",
        "routerImplementation": "0x3035c5428062B6f42cA1248baAF8Fa48338f1D7b",
        "feeRecipient": "0xd8F391e10223580611A70160d1D42bf55fCc882C",
        "migrationTarget": "0x3c5969d393197E42B4b5Fcc54055c361f2F6ACef",
        "uniswapV4PoolManager": "0xeDddAAF26109BF15E4701A61484b396DFf0A9968",
        "uniswapV4PositionManager": "0x94C6269f1D34AC47594c81c2feb9953E7cE7117E",
        "curve": {
          "k": "21000000000000000000000000",
          "s": "100000000000000000000",
          "feeBps": 30,
          "selfDeprecationBps": 8000,
          "maxBuyOkb": "10000000000000000000",
          "burnTaxMinBps": 0,
          "burnTaxMaxBps": 0
        }
      }
    ],
    "31337": [
      {
        "network": "anvil",
        "chainId": 31337,
        "commit": "d01e3e8",
        "deployedAt": "2026-05-21T12:33:46.185Z",
        "factory": "0x1613beB3B2C4f22Ee086B2b38C1476A3cE7f78E8",
        "proxyAdmin": "0x9467A509DA43CB50EB332187602534991Be1fEa4",
        "factoryImplementation": "0xf5059a5D33d5853360D16C683c16e67980206f36",
        "hookImplementation": "0x99bbA657f2BbC93c02D617f8bA121cB8Fc104Acf",
        "routerImplementation": "0x9E545E3C0baAB3E08CdfD552C960A1050f373042",
        "feeRecipient": "0x956A587c0e0A879c179939be9907E82aB8a7CB36",
        "migrationTarget": "0xc3e53F4d16Ae77Db1c982e75a937B9f60FE63690",
        "uniswapV4PoolManager": "0x67d269191c92Caf3cD7723F116c85e6E9bf55933",
        "uniswapV4PositionManager": "0xE6E340D132b5f46d1e472DebcD681B2aBc16e57E",
        "curve": {
          "k": "21000000000000000000000000",
          "s": "100000000000000000000",
          "feeBps": 30,
          "burnTaxMinBps": 100,
          "burnTaxMaxBps": 1000,
          "selfDeprecationBps": 8000,
          "maxBuyOkb": "10000000000000000000"
        }
      },
      {
        "network": "forge-local",
        "chainId": 31337,
        "commit": "d1b3a27",
        "deployedAt": "2026-05-12T15:54:00.000Z",
        "factory": "0x1F585372F116E1055AF2bED81a808DDf9638dCCD",
        "feeRecipient": "0xf39Fd6e51aad88F6F4ce6aB8827279cffFb92266",
        "migrationTarget": "0xd544d7A5EF50c510f3E90863828EAba7E392907A",
        "uniswapV4PoolManager": "0x70e754531418461eF2366b72cd396337d2AD6D5d",
        "uniswapV4PositionManager": "0xeF66010868Ff77119171628B7eFa0F6179779375",
        "curve": {
          "feeBps": 30,
          "k": "21000000000000000000000000",
          "maxBuyOkb": "10000000000000000000",
          "s": "100000000000000000000",
          "selfDeprecationBps": 8000,
          "burnTaxMinBps": 0,
          "burnTaxMaxBps": 0
        }
      }
    ],
    "11155111": [
      {
        "network": "sepolia",
        "chainId": 11155111,
        "commit": "71515d5",
        "deployedAt": "2026-05-16T12:46:02Z",
        "factory": "0x659B9e6BC036535f34597c8BCBC2051B964e4a7F",
        "proxyAdmin": "0x4dDAd72B990aA5b434A5B653556D420A232E5a81",
        "factoryImplementation": "0x347f98942EE95Db4A887aa892Be5B77322ac3d02",
        "hookImplementation": "0x7462d9c9522e66C824990f4E6805F3262093526c",
        "routerImplementation": "0x4Dd48d5929baFaBd10d18D976C8F6Af35f221852",
        "feeRecipient": "0x956A587c0e0A879c179939be9907E82aB8a7CB36",
        "migrationTarget": "0x8ca7F9C9D739C582c95B3A48f9F7668AFf1A2E78",
        "uniswapV4PoolManager": "0xE03A1074c86CFeDd5C142C4F04F1a1536e203543",
        "uniswapV4PositionManager": "0x429ba70129df741B2Ca2a85BC3A2a3328e5c09b4",
        "curve": {
          "feeBps": 30,
          "k": "21000000000000000000000000",
          "maxBuyOkb": "10000000000000000000",
          "s": "100000000000000000000",
          "selfDeprecationBps": 8000,
          "burnTaxMinBps": 100,
          "burnTaxMaxBps": 1000
        }
      }
    ]
  }
} as const;

export type EulrDeploymentNetwork = keyof typeof eulrDeployments.byNetwork;
export type EulrDeploymentChainId = keyof typeof eulrDeployments.byChainId;
