// Auto-generated by `npm run export:abis`. Do not edit by hand.
// Snapshot of every recorded deployment JSON under `deployments/<network>/latest.json`.

export const eulrDeployments = {
  "generatedAt": "2026-05-15T01:34:47.055Z",
  "generatedFrom": "deployments/<network>/latest.json + out/<Contract>.sol/<Contract>.json",
  "byNetwork": {
    "anvil": {
      "network": "anvil",
      "chainId": 31337,
      "commit": "417595f",
      "deployedAt": "2026-05-14T16:31:24.763Z",
      "factory": "0xe1DA8919f262Ee86f9BE05059C9280142CF23f48",
      "proxyAdmin": "0x36005A8e2295e5186699663a4f4D9CE3Da89Aefa",
      "factoryImplementation": "0xe1Aa25618fA0c7A1CFDab5d6B456af611873b629",
      "routerImplementation": "0x8ce361602B935680E8DeC218b820ff5056BeB7af",
      "feeRecipient": "0xa0Ee7A142d267C1f36714E4a8F75612F20a79720",
      "migrationTarget": "0xb19b36b1456E65E3A6D514D3F715f204BD59f431",
      "uniswapV4PoolManager": "0x700b6A60ce7EaaEA56F065753d8dcB9653dbAD35",
      "uniswapV4PositionManager": "0xA15BB66138824a1c7167f5E85b957d04Dd34E468",
      "curve": {
        "k": "21000000000000000000000000",
        "s": "100000000000000000000",
        "feeBps": 30,
        "selfDeprecationBps": 9900,
        "maxBuyOkb": "10000000000000000000"
      }
    },
    "forge-local": {
      "network": "forge-local",
      "chainId": 31337,
      "commit": "d1b3a27",
      "deployedAt": "2026-05-12T15:54:00.000Z",
      "factory": "0x1F585372F116E1055AF2bED81a808DDf9638dCCD",
      "feeRecipient": "0xf39Fd6e51aad88F6F4ce6aB8827279cffFb92266",
      "migrationTarget": "0xd544d7A5EF50c510f3E90863828EAba7E392907A",
      "uniswapV4PoolManager": "0x70e754531418461eF2366b72cd396337d2AD6D5d",
      "uniswapV4PositionManager": "0xeF66010868Ff77119171628B7eFa0F6179779375",
      "curve": {
        "feeBps": 30,
        "k": "21000000000000000000000000",
        "maxBuyOkb": "10000000000000000000",
        "s": "100000000000000000000",
        "selfDeprecationBps": 9900
      }
    },
    "hashkeytest": {
      "network": "hashkeytest",
      "chainId": 133,
      "commit": "417595f",
      "deployedAt": "2026-05-14T16:33:19.907Z",
      "factory": "0x726B98099fCA8a1778EAC863Bac1232A9753a55A",
      "proxyAdmin": "0x40Fb77DEB510584D878b73E676dC62c2EaebBc87",
      "factoryImplementation": "0xB1F5802db3bD3e66A19eAb72bFd65260F931A59F",
      "routerImplementation": "0x3035c5428062B6f42cA1248baAF8Fa48338f1D7b",
      "feeRecipient": "0xd8F391e10223580611A70160d1D42bf55fCc882C",
      "migrationTarget": "0x3c5969d393197E42B4b5Fcc54055c361f2F6ACef",
      "uniswapV4PoolManager": "0xeDddAAF26109BF15E4701A61484b396DFf0A9968",
      "uniswapV4PositionManager": "0x94C6269f1D34AC47594c81c2feb9953E7cE7117E",
      "curve": {
        "k": "21000000000000000000000000",
        "s": "100000000000000000000",
        "feeBps": 30,
        "selfDeprecationBps": 9900,
        "maxBuyOkb": "10000000000000000000"
      }
    }
  },
  "byChainId": {
    "133": [
      {
        "network": "hashkeytest",
        "chainId": 133,
        "commit": "417595f",
        "deployedAt": "2026-05-14T16:33:19.907Z",
        "factory": "0x726B98099fCA8a1778EAC863Bac1232A9753a55A",
        "proxyAdmin": "0x40Fb77DEB510584D878b73E676dC62c2EaebBc87",
        "factoryImplementation": "0xB1F5802db3bD3e66A19eAb72bFd65260F931A59F",
        "routerImplementation": "0x3035c5428062B6f42cA1248baAF8Fa48338f1D7b",
        "feeRecipient": "0xd8F391e10223580611A70160d1D42bf55fCc882C",
        "migrationTarget": "0x3c5969d393197E42B4b5Fcc54055c361f2F6ACef",
        "uniswapV4PoolManager": "0xeDddAAF26109BF15E4701A61484b396DFf0A9968",
        "uniswapV4PositionManager": "0x94C6269f1D34AC47594c81c2feb9953E7cE7117E",
        "curve": {
          "k": "21000000000000000000000000",
          "s": "100000000000000000000",
          "feeBps": 30,
          "selfDeprecationBps": 9900,
          "maxBuyOkb": "10000000000000000000"
        }
      }
    ],
    "31337": [
      {
        "network": "anvil",
        "chainId": 31337,
        "commit": "417595f",
        "deployedAt": "2026-05-14T16:31:24.763Z",
        "factory": "0xe1DA8919f262Ee86f9BE05059C9280142CF23f48",
        "proxyAdmin": "0x36005A8e2295e5186699663a4f4D9CE3Da89Aefa",
        "factoryImplementation": "0xe1Aa25618fA0c7A1CFDab5d6B456af611873b629",
        "routerImplementation": "0x8ce361602B935680E8DeC218b820ff5056BeB7af",
        "feeRecipient": "0xa0Ee7A142d267C1f36714E4a8F75612F20a79720",
        "migrationTarget": "0xb19b36b1456E65E3A6D514D3F715f204BD59f431",
        "uniswapV4PoolManager": "0x700b6A60ce7EaaEA56F065753d8dcB9653dbAD35",
        "uniswapV4PositionManager": "0xA15BB66138824a1c7167f5E85b957d04Dd34E468",
        "curve": {
          "k": "21000000000000000000000000",
          "s": "100000000000000000000",
          "feeBps": 30,
          "selfDeprecationBps": 9900,
          "maxBuyOkb": "10000000000000000000"
        }
      },
      {
        "network": "forge-local",
        "chainId": 31337,
        "commit": "d1b3a27",
        "deployedAt": "2026-05-12T15:54:00.000Z",
        "factory": "0x1F585372F116E1055AF2bED81a808DDf9638dCCD",
        "feeRecipient": "0xf39Fd6e51aad88F6F4ce6aB8827279cffFb92266",
        "migrationTarget": "0xd544d7A5EF50c510f3E90863828EAba7E392907A",
        "uniswapV4PoolManager": "0x70e754531418461eF2366b72cd396337d2AD6D5d",
        "uniswapV4PositionManager": "0xeF66010868Ff77119171628B7eFa0F6179779375",
        "curve": {
          "feeBps": 30,
          "k": "21000000000000000000000000",
          "maxBuyOkb": "10000000000000000000",
          "s": "100000000000000000000",
          "selfDeprecationBps": 9900
        }
      }
    ]
  }
} as const;

export type EulrDeploymentNetwork = keyof typeof eulrDeployments.byNetwork;
export type EulrDeploymentChainId = keyof typeof eulrDeployments.byChainId;
