// Auto-generated by `npm run export:abis`. Do not edit by hand.
// Snapshot of every recorded deployment JSON under `deployments/<network>/latest.json`.

export const eulrDeployments = {
  "generatedAt": "2026-05-16T12:48:10.446Z",
  "generatedFrom": "deployments/<network>/latest.json + out/<Contract>.sol/<Contract>.json",
  "byNetwork": {
    "anvil": {
      "network": "anvil",
      "chainId": 31337,
      "commit": "71515d5",
      "deployedAt": "2026-05-16T08:50:13.081Z",
      "factory": "0x5FC8d32690cc91D4c39d9d3abcBD16989F875707",
      "proxyAdmin": "0x61c36a8d610163660E21a8b7359e1Cac0C9133e1",
      "factoryImplementation": "0xDc64a140Aa3E981100a9becA4E685f962f0cF6C9",
      "routerImplementation": "0xCf7Ed3AccA5a467e9e704C703E8D87F634fB0Fc9",
      "feeRecipient": "0x956A587c0e0A879c179939be9907E82aB8a7CB36",
      "migrationTarget": "0x9fE46736679d2D9a65F0992F2272dE9f3c7fa6e0",
      "uniswapV4PoolManager": "0x5FbDB2315678afecb367f032d93F642f64180aa3",
      "uniswapV4PositionManager": "0xe7f1725E7734CE288F8367e1Bb143E90bb3F0512",
      "curve": {
        "k": "21000000000000000000000000",
        "s": "100000000000000000000",
        "feeBps": 30,
        "selfDeprecationBps": 8000,
        "maxBuyOkb": "10000000000000000000"
      }
    },
    "forge-local": {
      "network": "forge-local",
      "chainId": 31337,
      "commit": "d1b3a27",
      "deployedAt": "2026-05-12T15:54:00.000Z",
      "factory": "0x1F585372F116E1055AF2bED81a808DDf9638dCCD",
      "feeRecipient": "0xf39Fd6e51aad88F6F4ce6aB8827279cffFb92266",
      "migrationTarget": "0xd544d7A5EF50c510f3E90863828EAba7E392907A",
      "uniswapV4PoolManager": "0x70e754531418461eF2366b72cd396337d2AD6D5d",
      "uniswapV4PositionManager": "0xeF66010868Ff77119171628B7eFa0F6179779375",
      "curve": {
        "feeBps": 30,
        "k": "21000000000000000000000000",
        "maxBuyOkb": "10000000000000000000",
        "s": "100000000000000000000",
        "selfDeprecationBps": 8000
      }
    },
    "hashkeytest": {
      "network": "hashkeytest",
      "chainId": 133,
      "commit": "417595f",
      "deployedAt": "2026-05-14T16:33:19.907Z",
      "factory": "0x726B98099fCA8a1778EAC863Bac1232A9753a55A",
      "proxyAdmin": "0x40Fb77DEB510584D878b73E676dC62c2EaebBc87",
      "factoryImplementation": "0xB1F5802db3bD3e66A19eAb72bFd65260F931A59F",
      "routerImplementation": "0x3035c5428062B6f42cA1248baAF8Fa48338f1D7b",
      "feeRecipient": "0xd8F391e10223580611A70160d1D42bf55fCc882C",
      "migrationTarget": "0x3c5969d393197E42B4b5Fcc54055c361f2F6ACef",
      "uniswapV4PoolManager": "0xeDddAAF26109BF15E4701A61484b396DFf0A9968",
      "uniswapV4PositionManager": "0x94C6269f1D34AC47594c81c2feb9953E7cE7117E",
      "curve": {
        "k": "21000000000000000000000000",
        "s": "100000000000000000000",
        "feeBps": 30,
        "selfDeprecationBps": 8000,
        "maxBuyOkb": "10000000000000000000"
      }
    },
    "sepolia": {
      "network": "sepolia",
      "chainId": 11155111,
      "commit": "71515d5",
      "deployedAt": "2026-05-16T12:46:02Z",
      "factory": "0x659B9e6BC036535f34597c8BCBC2051B964e4a7F",
      "proxyAdmin": "0x4dDAd72B990aA5b434A5B653556D420A232E5a81",
      "factoryImplementation": "0x3bdD387d346Fe7FF9b80186D1EaB067939393658",
      "routerImplementation": "0x4Dd48d5929baFaBd10d18D976C8F6Af35f221852",
      "feeRecipient": "0x956A587c0e0A879c179939be9907E82aB8a7CB36",
      "migrationTarget": "0x8ca7F9C9D739C582c95B3A48f9F7668AFf1A2E78",
      "uniswapV4PoolManager": "0xE03A1074c86CFeDd5C142C4F04F1a1536e203543",
      "uniswapV4PositionManager": "0x429ba70129df741B2Ca2a85BC3A2a3328e5c09b4",
      "curve": {
        "feeBps": 30,
        "k": "21000000000000000000000000",
        "maxBuyOkb": "10000000000000000000",
        "s": "100000000000000000000",
        "selfDeprecationBps": 8000
      }
    }
  },
  "byChainId": {
    "133": [
      {
        "network": "hashkeytest",
        "chainId": 133,
        "commit": "417595f",
        "deployedAt": "2026-05-14T16:33:19.907Z",
        "factory": "0x726B98099fCA8a1778EAC863Bac1232A9753a55A",
        "proxyAdmin": "0x40Fb77DEB510584D878b73E676dC62c2EaebBc87",
        "factoryImplementation": "0xB1F5802db3bD3e66A19eAb72bFd65260F931A59F",
        "routerImplementation": "0x3035c5428062B6f42cA1248baAF8Fa48338f1D7b",
        "feeRecipient": "0xd8F391e10223580611A70160d1D42bf55fCc882C",
        "migrationTarget": "0x3c5969d393197E42B4b5Fcc54055c361f2F6ACef",
        "uniswapV4PoolManager": "0xeDddAAF26109BF15E4701A61484b396DFf0A9968",
        "uniswapV4PositionManager": "0x94C6269f1D34AC47594c81c2feb9953E7cE7117E",
        "curve": {
          "k": "21000000000000000000000000",
          "s": "100000000000000000000",
          "feeBps": 30,
          "selfDeprecationBps": 8000,
          "maxBuyOkb": "10000000000000000000"
        }
      }
    ],
    "31337": [
      {
        "network": "anvil",
        "chainId": 31337,
        "commit": "71515d5",
        "deployedAt": "2026-05-16T08:50:13.081Z",
        "factory": "0x5FC8d32690cc91D4c39d9d3abcBD16989F875707",
        "proxyAdmin": "0x61c36a8d610163660E21a8b7359e1Cac0C9133e1",
        "factoryImplementation": "0xDc64a140Aa3E981100a9becA4E685f962f0cF6C9",
        "routerImplementation": "0xCf7Ed3AccA5a467e9e704C703E8D87F634fB0Fc9",
        "feeRecipient": "0x956A587c0e0A879c179939be9907E82aB8a7CB36",
        "migrationTarget": "0x9fE46736679d2D9a65F0992F2272dE9f3c7fa6e0",
        "uniswapV4PoolManager": "0x5FbDB2315678afecb367f032d93F642f64180aa3",
        "uniswapV4PositionManager": "0xe7f1725E7734CE288F8367e1Bb143E90bb3F0512",
        "curve": {
          "k": "21000000000000000000000000",
          "s": "100000000000000000000",
          "feeBps": 30,
          "selfDeprecationBps": 8000,
          "maxBuyOkb": "10000000000000000000"
        }
      },
      {
        "network": "forge-local",
        "chainId": 31337,
        "commit": "d1b3a27",
        "deployedAt": "2026-05-12T15:54:00.000Z",
        "factory": "0x1F585372F116E1055AF2bED81a808DDf9638dCCD",
        "feeRecipient": "0xf39Fd6e51aad88F6F4ce6aB8827279cffFb92266",
        "migrationTarget": "0xd544d7A5EF50c510f3E90863828EAba7E392907A",
        "uniswapV4PoolManager": "0x70e754531418461eF2366b72cd396337d2AD6D5d",
        "uniswapV4PositionManager": "0xeF66010868Ff77119171628B7eFa0F6179779375",
        "curve": {
          "feeBps": 30,
          "k": "21000000000000000000000000",
          "maxBuyOkb": "10000000000000000000",
          "s": "100000000000000000000",
          "selfDeprecationBps": 8000
        }
      }
    ],
    "11155111": [
      {
        "network": "sepolia",
        "chainId": 11155111,
        "commit": "71515d5",
        "deployedAt": "2026-05-16T12:46:02Z",
        "factory": "0x659B9e6BC036535f34597c8BCBC2051B964e4a7F",
        "proxyAdmin": "0x4dDAd72B990aA5b434A5B653556D420A232E5a81",
        "factoryImplementation": "0x3bdD387d346Fe7FF9b80186D1EaB067939393658",
        "routerImplementation": "0x4Dd48d5929baFaBd10d18D976C8F6Af35f221852",
        "feeRecipient": "0x956A587c0e0A879c179939be9907E82aB8a7CB36",
        "migrationTarget": "0x8ca7F9C9D739C582c95B3A48f9F7668AFf1A2E78",
        "uniswapV4PoolManager": "0xE03A1074c86CFeDd5C142C4F04F1a1536e203543",
        "uniswapV4PositionManager": "0x429ba70129df741B2Ca2a85BC3A2a3328e5c09b4",
        "curve": {
          "feeBps": 30,
          "k": "21000000000000000000000000",
          "maxBuyOkb": "10000000000000000000",
          "s": "100000000000000000000",
          "selfDeprecationBps": 8000
        }
      }
    ]
  }
} as const;

export type EulrDeploymentNetwork = keyof typeof eulrDeployments.byNetwork;
export type EulrDeploymentChainId = keyof typeof eulrDeployments.byChainId;
