import { mkdirSync, readdirSync, writeFileSync } from "node:fs";
import { join } from "node:path";
import type { Abi } from "viem";
import { readArtifact } from "../lib/artifacts.js";
import { artifacts } from "../config/artifacts.js";
import { readDeployment, type Deployment } from "../config/deployments.js";
import { getArg } from "../lib/args.js";

type ExportContract = {
  name: string;
  artifact: string;
  description: string;
};

const CONTRACT_EXPORTS: ExportContract[] = [
  {
    name: "EulrFactory",
    artifact: artifacts.factory,
    description: "Singleton factory. Creates per-token (token, hook, router) trios and exposes the read registry.",
  },
  {
    name: "EulrHook",
    artifact: "EulrHook.sol/EulrHook.json",
    description: "Per-token bonding-curve engine. Owns curve state, fee accrual, self-deprecation, and one-shot migration.",
  },
  {
    name: "EulrRouter",
    artifact: "EulrRouter.sol/EulrRouter.json",
    description: "Per-token user entrypoint. Wraps buy/sell so frontends interact with a stable interface per token.",
  },
  {
    name: "EulrToken",
    artifact: "EulrToken.sol/EulrToken.json",
    description: "Per-token ERC-20. Mint and burn are gated to the bound hook; transfer/approve match the standard ABI.",
  },
  {
    name: "UniswapV4MintPositionTarget",
    artifact: artifacts.uniswapV4MintPositionTarget,
    description: "Reference migration adapter. Encodes Uniswap v4 MINT_POSITION/SETTLE_PAIR and burns the LP to address(0x..dEaD).",
  },
];

type AbiOutput = {
  name: string;
  description: string;
  abi: Abi;
};

type AddressesShape = {
  generatedAt: string;
  generatedFrom: string;
  byNetwork: Record<string, NetworkDeployment>;
  // Multiple networks can share a chain id (e.g. local anvil + forge-local both
  // use 31337). Callers should disambiguate by `network` name; for the common
  // case of a single deployment per chain id, `byChainId[id][0]` is sufficient.
  byChainId: Record<string, NetworkDeployment[]>;
};

type NetworkDeployment = {
  network: string;
  chainId: number;
  commit: string;
  deployedAt: string;
  factory: `0x${string}`;
  feeRecipient: `0x${string}`;
  migrationTarget: `0x${string}`;
  uniswapV4PoolManager: `0x${string}`;
  uniswapV4PositionManager: `0x${string}`;
  curve: Deployment["curve"];
};

const outputDir = join(process.cwd(), getArg("out", "frontend/abi"));
mkdirSync(outputDir, { recursive: true });

const abiOutputs: AbiOutput[] = CONTRACT_EXPORTS.map((entry) => {
  const artifact = readArtifact(entry.artifact);
  return { name: entry.name, description: entry.description, abi: artifact.abi };
});

for (const entry of abiOutputs) {
  const path = join(outputDir, `${entry.name}.json`);
  writeFileSync(path, `${JSON.stringify(entry.abi, null, 2)}\n`);
}

const indexTs = renderIndexTs(abiOutputs);
writeFileSync(join(outputDir, "index.ts"), indexTs);

const addresses = collectAddresses();
writeFileSync(join(outputDir, "addresses.json"), `${JSON.stringify(addresses, null, 2)}\n`);
writeFileSync(join(outputDir, "addresses.ts"), renderAddressesTs(addresses));

const readme = renderReadme(abiOutputs, addresses);
writeFileSync(join(outputDir, "README.md"), readme);

console.log(
  JSON.stringify(
    {
      outputDir,
      contracts: abiOutputs.map((entry) => ({
        name: entry.name,
        functions: entry.abi.filter((item) => item.type === "function").length,
        events: entry.abi.filter((item) => item.type === "event").length,
        errors: entry.abi.filter((item) => item.type === "error").length,
      })),
      networks: Object.keys(addresses.byNetwork),
    },
    null,
    2,
  ),
);

function renderIndexTs(entries: AbiOutput[]): string {
  const header = [
    "// Auto-generated by `npm run export:abis`. Do not edit by hand.",
    "// Each ABI is inlined as a `const` array so viem / wagmi infer argument and",
    "// return types directly from the literal shape.",
    "",
    'import type { Abi } from "viem";',
    "",
  ].join("\n");

  const constNames: string[] = [];
  const bodies = entries.map((entry) => {
    const constName = `${camelCase(entry.name)}Abi`;
    constNames.push(constName);
    const inlined = JSON.stringify(entry.abi, null, 2);
    return [
      `// ${entry.description}`,
      `export const ${constName} = ${inlined} as const satisfies Abi;`,
      "",
    ].join("\n");
  });

  const exportsBlock = [
    "export const eulrAbis = {",
    ...entries.map((entry) => `  ${entry.name}: ${camelCase(entry.name)}Abi,`),
    "} as const;",
    "",
    `export type EulrContractName = keyof typeof eulrAbis;`,
    "",
  ].join("\n");

  return [header, ...bodies, exportsBlock].join("\n");
}

function renderAddressesTs(addresses: AddressesShape): string {
  return [
    "// Auto-generated by `npm run export:abis`. Do not edit by hand.",
    "// Snapshot of every recorded deployment JSON under `deployments/<network>/latest.json`.",
    "",
    `export const eulrDeployments = ${JSON.stringify(addresses, null, 2)} as const;`,
    "",
    "export type EulrDeploymentNetwork = keyof typeof eulrDeployments.byNetwork;",
    "export type EulrDeploymentChainId = keyof typeof eulrDeployments.byChainId;",
    "",
  ].join("\n");
}

function renderReadme(entries: AbiOutput[], addresses: AddressesShape): string {
  const networkLines = Object.values(addresses.byNetwork)
    .map((deployment) =>
      `| ${deployment.network} | ${deployment.chainId} | ${deployment.factory} | ${deployment.migrationTarget} |`,
    )
    .join("\n");

  const contractLines = entries
    .map((entry) => `- \`${entry.name}.json\` — ${entry.description}`)
    .join("\n");

  return [
    "# Eulr Frontend ABI Bundle",
    "",
    "Generated from `out/` Foundry artifacts and `deployments/<network>/latest.json` via",
    "`npm run export:abis`. Re-run after every contract or deployment change.",
    "",
    "## Files",
    "",
    contractLines,
    "- `index.ts` — typed `as const` ABIs for viem / wagmi.",
    "- `addresses.json` / `addresses.ts` — deployment addresses, chain ids, curve params.",
    "",
    "## Networks",
    "",
    "| Network | Chain ID | Factory | Migration Target |",
    "| --- | --- | --- | --- |",
    networkLines || "| _(no deployments recorded yet)_ | | | |",
    "",
    "See `FRONTEND_INTEGRATION.md` at the repository root for the full integration guide.",
    "",
  ].join("\n");
}

function collectAddresses(): AddressesShape {
  const root = join(process.cwd(), "deployments");
  const byNetwork: Record<string, NetworkDeployment> = {};
  const byChainId: Record<string, NetworkDeployment[]> = {};

  let networks: string[];
  try {
    networks = readdirSync(root, { withFileTypes: true })
      .filter((entry) => entry.isDirectory())
      .map((entry) => entry.name);
  } catch {
    networks = [];
  }

  for (const network of networks) {
    let deployment: Deployment;
    try {
      deployment = readDeployment(network);
    } catch {
      continue;
    }

    const entry: NetworkDeployment = {
      network,
      chainId: deployment.chainId,
      commit: deployment.commit,
      deployedAt: deployment.deployedAt,
      factory: deployment.factory,
      feeRecipient: deployment.feeRecipient,
      migrationTarget: deployment.migrationTarget,
      uniswapV4PoolManager: deployment.uniswapV4PoolManager,
      uniswapV4PositionManager: deployment.uniswapV4PositionManager,
      curve: deployment.curve,
    };
    byNetwork[network] = entry;
    const chainKey = String(deployment.chainId);
    const list = byChainId[chainKey] ?? [];
    list.push(entry);
    byChainId[chainKey] = list;
  }

  return {
    generatedAt: new Date().toISOString(),
    generatedFrom: "deployments/<network>/latest.json + out/<Contract>.sol/<Contract>.json",
    byNetwork,
    byChainId,
  };
}

function camelCase(name: string): string {
  return name.charAt(0).toLowerCase() + name.slice(1);
}
